//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernCashFlow.Globalization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernCashFlow.Globalization.Resources.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Transfer Code.
        /// </summary>
        public static string AccountTransferCode {
            get {
                return ResourceManager.GetString("AccountTransferCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Value.
        /// </summary>
        public static string ActualValue {
            get {
                return ResourceManager.GetString("ActualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Number.
        /// </summary>
        public static string CheckNumber {
            get {
                return ResourceManager.GetString("CheckNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Status.
        /// </summary>
        public static string EditStatus {
            get {
                return ResourceManager.GetString("EditStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Value.
        /// </summary>
        public static string ExpectedValue {
            get {
                return ResourceManager.GetString("ExpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Ninject library..
        /// </summary>
        public static string Failed_to_load_Ninject {
            get {
                return ResourceManager.GetString("Failed_to_load_Ninject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Recurring.
        /// </summary>
        public static string IsRecurring {
            get {
                return ResourceManager.GetString("IsRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Interval.
        /// </summary>
        public static string MonthlyInterval {
            get {
                return ResourceManager.GetString("MonthlyInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction code is null..
        /// </summary>
        public static string NullTransactionCode {
            get {
                return ResourceManager.GetString("NullTransactionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Installments.
        /// </summary>
        public static string RemainingInstallments {
            get {
                return ResourceManager.GetString("RemainingInstallments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        public static string ResponsibleName {
            get {
                return ResourceManager.GetString("ResponsibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports DrillDown.
        /// </summary>
        public static string SupportsDrillDown {
            get {
                return ResourceManager.GetString("SupportsDrillDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalization Test.
        /// </summary>
        public static string TesteGlobalizacao {
            get {
                return ResourceManager.GetString("TesteGlobalizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Code.
        /// </summary>
        public static string TransactionCode {
            get {
                return ResourceManager.GetString("TransactionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Group.
        /// </summary>
        public static string TransactionGroup {
            get {
                return ResourceManager.GetString("TransactionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Status.
        /// </summary>
        public static string TransactionStatusDescription {
            get {
                return ResourceManager.GetString("TransactionStatusDescription", resourceCulture);
            }
        }
    }
}
